###
GET localhost:3000/api/students/

###
POST localhost:3000/api/students/create
Content-Type: application/json
{
    "name": "Dev test",
    "email": "devtest@dev.com",
    "age": 20,
    "dob": "1999-01-01",
}

###
GET localhost:3000/api/students/5

###
DELETE localhost:3000/api/students/delete/12

###
GET localhost:3000/api/students/migrate

###
GET localhost:3000/api/students/seed

###
GET localhost:3000/api/students/drop
